#!/usr/bin/env bash

# export PATH=$PATH:/run/host/usr/bin
export G_MESSAGES_DEBUG="re.sonny.Junction"
export XDG_DATA_DIRS="${XDG_DATA_DIRS:-/usr/local/share:/usr/share}:/run/host/usr/share:/var/lib/snapd/desktop:/var/lib/flatpak/exports/share:${HOME}/.local/share/flatpak/exports/share"
export GI_TYPELIB_PATH="$GI_TYPELIB_PATH:/usr/lib/x86_64-linux-gnu/girepository-1.0/"
re.sonny.Junction "$@"
